### ISSUE TITLE
I think you should provide some hints for the questions?

### ISSUE THREAD

**Issue by yhuanghamu** [callumacrae/tryregex#20]

**Comment by yhuanghamu** [comment]
I got stuck in this question, "Quantifiers", but there is no hint on how to solve it.

**Comment by adamhipster** [comment]
I got stuck on a part too, so I just looked into the source code by using Chrome Developer Tools to see the javascript code for the answers that he was using. In my particular case, I found that my regex was correct but that I shouldn't use the answer() call. I read the question wrong.

I don't know if I'm allowed to post the link, so I won't. If you know HTML, then you can (eventually) find it.

**Comment by callumacrae** [comment]
The `showAnswer()` function will show you the answer :)
